.TH "EarthCard" 3 "Fri May 7 2021" "Version 0.2" "Hello" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EarthCard
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEarthCard\fP (\fBString\fP)"
.br
.ti -1c
.RI "\fBEarthCard\fP (\fBString\fP, size_t)"
.br
.ti -1c
.RI "\fBEarthCard\fP (\fBString\fP, size_t, size_t)"
.br
.ti -1c
.RI "void \fBchangeCardName\fP (\fBString\fP)"
.br
.ti -1c
.RI "void \fBchangeBaseDemage\fP (size_t)"
.br
.ti -1c
.RI "void \fBchangeBonusDemage\fP (size_t)"
.br
.ti -1c
.RI "void \fBaddPower\fP (int)"
.br
.ti -1c
.RI "\fBString\fP \fBseeCardName\fP () const"
.br
.ti -1c
.RI "size_t \fBBaseDemage\fP () const"
.br
.ti -1c
.RI "size_t \fBBonusDemage\fP () const"
.br
.ti -1c
.RI "size_t \fBCardType\fP () const"
.br
.ti -1c
.RI "\fBString\fP \fBseeCardType\fP () const"
.br
.ti -1c
.RI "size_t \fBOverallDemage\fP () const"
.br
.ti -1c
.RI "\fBEarthCard\fP & \fBoperator=\fP (const \fBEarthCard\fP &)"
.br
.ti -1c
.RI "void \fBFullStats\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file EarthCard\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Hello from the source code\&.
